spring:
  application:
    name: backend
  profiles:
    default: local

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flowdeck}
    username: ${DB_USERNAME:flowdeck}
    password: ${DB_PASSWORD:flowdeck}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    properties:
      hibernate:
        format_sql: true
